import classNames from "classnames";
import ReactPlayer from "react-player";
import { headingTextStyle } from "./styles";
import ScreenLayout from "../components/ScreenLayout";
import { useState } from "react";

export default function Publish() {
  const [title, setTitle] = useState("");
  const [desc, setDesc] = useState("");
  return (
    <ScreenLayout>
      <h1 className={classNames(headingTextStyle)}>Publish Your Lesson</h1>
      <div className="h-10" />
      <div className="flex-col flex space-y-5">
        <span className="font-bold text-2xl">
          Part 3: How to Make a Thumbnail
        </span>
        <div className="flex flex-col space-y-5 w-3/4">
          <div className="flex w-full items-center justify-center">
            <ReactPlayer
              className="react-player"
              url="videos/test.mp4"
              width="75%"
              height="75%"
              controls={true}
            />
          </div>
          <span className="text-lg">
            In this lesson, you will learn how to edit clickable thumbnails.
            Thumbnails are a crucial part of an creator’s toolbox. They allow
            the audience to get a peak at what type of content you can provide.
            More importantly, they are what users see before deciding on whether
            or not to click on your content.
          </span>
          <div className="inline-flex space-x-2 items-center">
            <span className="text-lg font-bold">Lesson Summary</span>
            <button className="btn btn-sm gap-2">
              Regenerate
              <svg
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                viewBox="0 0 24 24"
                height="1em"
                width="1em"
              >
                <path d="M1 4v6h6M23 20v-6h-6" />
                <path d="M20.49 9A9 9 0 005.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 013.51 15" />
              </svg>
            </button>
          </div>
          <span className="text-lg">
            The lesson discusses how to create and customize YouTube thumbnails,
            which play a significant role in enticing viewers to click on a
            video. Thumbnails are still images that represent the video content,
            and there are two types: auto-generated by YouTube and created by
            the video owner. While auto-generated thumbnails save time,
            personalized thumbnails let you add your own branding and style. Six
            recommendations for creating professional thumbnails are given,
            including dimensions, font guidelines, branding, readability,
            high-quality images, and thumbnail style experimentation. Busy
            thumbnails should be avoided, and the article concludes with tips
            for uploading customized thumbnails to YouTube. The article also
            includes frequently asked questions about using templates, the
            number of custom thumbnails a channel can upload per day, editing
            published video thumbnails, and the use of clickbait thumbnails.
          </span>
          <div className="inline-flex space-x-2 items-center">
            <span className="text-lg font-bold">Lesson Quiz</span>
            <button className="btn btn-sm gap-2">
              Regenerate
              <svg
                fill="none"
                stroke="currentColor"
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                viewBox="0 0 24 24"
                height="1em"
                width="1em"
              >
                <path d="M1 4v6h6M23 20v-6h-6" />
                <path d="M20.49 9A9 9 0 005.64 5.64L1 10m22 4l-4.64 4.36A9 9 0 013.51 15" />
              </svg>
            </button>
          </div>
          <span className="text-lg">
            1. What are the two types of YouTube thumbnail styles creators can
            choose from? <br />
            a) Pictures and videos <br />
            b) Auto-generated from YouTube and created by you <br />
            c) Thumbnail and full-screen mode <br />
            d) High-quality and low-quality <br />
            2. What is the recommended dimension for YouTube thumbnails?
            <br />
            a) 720 x 480 pixels <br />
            b) 640 x 480 pixels <br />
            c) 1280 x 720 pixels <br />
            d) 1920 x 1080 pixels <br />
            3. What should be included in a YouTube thumbnail to make it more
            clickable? <br />
            a) Hard to read text <br />
            b) Low-quality and irrelevant images <br />
            c) Consistent branded theme, font, color scheme, and graphics
            <br />
            d) Small and unreadable images <br />
            4. What is the recommended YouTube thumbnail font guideline?
            <br />
            a) Any font and text color <br />
            b) Bold, block fonts <br />
            c) Only bright colors <br />
            d) Italics and cursive <br />
            5. Can you change a YouTube video's thumbnail after publishing a
            video? <br />
            a) Yes <br />
            b) No <br />
            c) Only in the first hour after publishing <br />
            d) Only with a verified account
          </span>
        </div>
      </div>
      <div className="w-full h-10" />
      <div className="w-full flex items-center justify-center">
        <button className="btn btn-lg border-none rounded-md bg-gradient-to-r from-[#00df16] to-[#08bad2]">
          Publish Now
        </button>
      </div>
    </ScreenLayout>
  );
}
